Django/03-28/articles/urls.py
from django.urls import path

# . : 현재 디렉토리리
from . import views

# {% url namespace:name %}
# app_name = 'namespace'
app_name = 'articles'

urlpatterns = [
    # READ
    # 전체 게시글 조회
    path('', views.index, name = 'index'),
    # 단일 게시글 조회
    # variable routing <데이터타입:변수>
    path('<int:pk>/', views.detail, name='detail'),

    # CREATE
    # 렌더링 (생성 페이지를 보여줄거다)
    path('new/', views.new, name = 'new'),
    # 리다이렉트 (생성 버튼을 눌렀을 때 게시글이 생성)
    path('create/', views.create, name = 'create'),

    # DELETE
    # 단일 게시글 조회 후 삭제
    # variable routing <데이터타입:변수>
    path('<int:pk>/delete/', views.delete, name='delete'),

    # UPDATE
    # 단일 게시글 조회 후 수정
    # variable routing <데이터타입:변수>
    # 페이지 렌더링
    path('<int:pk>/edit/', views.edit, name='edit'),
    # 페이지 리다이렉트
    path('<int:pk>/update/', views.update, name='update'),
]

Django/03-28/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    # id = models.AutoField(primary_key=True)
    # 제목은 글자 제한을 20글자
    # 왜 게시글의 제목은 글자제한을 둬야할까?
    title = models.CharField(max_length=20)
    # 게시글 내용(글자 제한 x)
    content = models.TextField()
    # auto_now_add : 객체가 처음 생성될때 시간
    created_at = models.DateTimeField(auto_now_add=True)
    # auto_now : 객체가 저장 될 때의 현재 시간
    updated_at = models.DateTimeField(auto_now=True)


# ORM
# DB는 SQL쿼리로 조작
# Django는 python
# : python 코드를 SQL쿼리로 변환해주는 도구
# 왜 ORM을 쓸까?
# 우리 사용하는 Django는 python // DB는 SQL
# QuerySet API
# : 이 구문을 사용하면 DB에 데이터를 접근하고, 조작(CRUD)할 수 있다.
# ex) Article.obects.all()


# Create (객체생성)
# 1. 첫 번째 방법

# article = Board()
# article.title = 'first'
# article.content = 'hello'
# article.save()

# 2. 두 번째 방법

# article = Board(title = 'second', content = 'hi')
# article.save()

# 3. 세 번째 방법

# Board.objects.create(title = 'third', content = 'byebye')

# Q) 우리는 객체를 생성할 때 1번, 2번, 3번 방법
# 몇번 방법을 써야할까?? // 몇번 방법을 지양해야할까??
# 3번 방법은 지양, 왜??
# 객체를 저장하기전에 데이터를 검증하고 그다음에 save()
# 검증단계 : 유효성 검사(validation check)... 등등


# Read (조회)

# 1. 전체 조회

# Board.objects.all()

# 2. 특정 조건으로 데이터 조회(filter)
# Board.objects.filter(title = 'first')
# Board.objects.filter(content__contains='he')
# Board.objects.filter(title__startswith='f')

# 조회한 객체가 없을경우 예외 발생 X

# 3. 단일 데이터 조회(get)
# Board.obejects.get(pk=1)
# Board.obejects.get(title='first')

# Board.obejects.get(title='fir') ---> 에러

# 조회한 객체가 없을경우 예외 발생 O
# 조회하는 객체가 두개 이상이다. 예외 발생 O
# 고유성을 보장하는 조회.

# Update (수정)
# article = Board.objects.get(pk=1)
# article.title = 'first1'
# article.save()


# Delete (삭제)

# article = Board.objects.get(pk=1)
# article.delete()

# 만약 새로운 객체를 생성하면 pk=1로 생성되는게 아니라
# pk=4로 생성된다.

# 추가적으로 QuerySetAPI 공부는 Django 공식문서 확인인

Django/03-28/articles/views.py
from django.shortcuts import render, redirect

# 현재 디렉토리의 models.py로 부터 Board 모델을 가져오겠다. 
from .models import Article

def index(request):
    # QuerySetAPI ---> Read, 전체 데이터 조회 : Board.objects.all()
    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, 'articles/index.html', context)

def detail(request, pk):
    # QuerySet API : 단일 데이터 조회 : get
    article = Article.objects.get(pk = pk)
    context = {
        'article' : article
    }

    return render(request, 'articles/detail.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    # 객체생성 방법 : 1번 방법, 2번방법, 3번방법(3번은 지양)
    # save()하기 전에 유효성 검사를 해야한다.
    # form태그의 name으로 조회
    title = request.POST.get('title')
    content = request.POST.get('content')

    # GET 방식: url에 노출 - 데이터 조회, 검색할 때 사용
    # POST 방식: url에 노출 x (보안성) - 데이터 생성, 수정, 삭제할 때 사용
    # POST 방식이 좋지만 GET 방식을 쓰는 이유
    # GET 방식에 비해 POST 방식이 훨씬 복잡하다. : csrf토큰 - 보안토큰 

    # 2번 방법(안정성, 코드간결)
    article = Article(title = title, content = content)
    # 데이터를 DB에 함부로 저장하면 안된다.
    # save하기 전에 유효성 검사
    article.save()

    # render, redirect 차이
    # 우리가 사용자에게 새로운 페이지를 보여줄 때 사용(렌더링) : render
    # 데이터 처리 후(생성, 수정, 삭제) 다른 페이지로 이동할 때 : redirect
    return redirect('articles:detail', article.pk)

# 단일 게시글 조회 후 삭제
def delete(request, pk):
    # QuerySetAPI
    article = Article.objects.get(pk = pk)
    article.delete()

    return redirect('articles:index')

# 페이지 렌더링(게시글 조회부터)
def edit(request, pk):
    article = Article.objects.get(pk = pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

# 페이지 리다이렉트(create와 차이 : 기존에 있던 게시글을 변경)
def update(request, pk):
    article = Article.objects.get(pk = pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')

    article.save()
    
    # 데이터가 변경되었으니 render가 아니라 redirect
    return redirect('articles:detail', article.pk)

Django/03-28/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}
<h2>Detail 페이지</h2>
<h3>{{article.pk}}번째 게시글</h3>

<hr>

<p>제목 : {{article.title}}</p>
<p>내용 : {{article.content}}</p>
<p>작성 시각 : {{article.created_at}}</p>
<p>수정 시각 : {{article.updated_at}}</p>

<hr>

<a href="{% url "articles:index" %}"> Home </a>

<hr>

<form action="{% url "articles:delete" article.pk %}" method = 'POST'>
    {% csrf_token %}
    <input type="submit" value='DELETE'>
</form>

<hr>

{% comment %} edit 버튼 {% endcomment %}
<a href="{% url "articles:edit" article.pk %}">EDIT</a>

{% endblock content %}

Django/03-28/articles/templates/articles/edit.html
{% extends "base.html" %}

{% block content %}
<h1>Edit</h1>

<form action="{% url "articles:update" article.pk %}" method='POST'>
    {% csrf_token %}
    <label for="title">Title : </label>
    <input type="text" name='title' value="{{article.title}}">

    <label for="content">Content : </label>
    <textarea name="content">{{article.content}}</textarea>

    <input type="submit">
</form>

<hr>
{% comment %} HOME 버튼 {% endcomment %}
<a href="{% url "articles:index" %}">HOME</a>
{% endblock content %}

Django/03-28/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
    <h1>게시판</h1>

    <hr>
        <a href="{% url "articles:new" %}">글쓰기</a>
    <hr>
    
    {% comment %} DTL : for문 {% endcomment %}
    {% for article in  articles %}
        {% comment %} {{객체.속성}} {% endcomment %}
        <p>글 id : {{article.pk}}</p>
        {% comment %} a태그로 감싸면 링크로 이동하게 만들 수 있다. {% endcomment %}
        <a href="{% url "articles:detail" article.pk %}">
            <p>글 제목 : {{article.title}}</p>
        </a>
        <p>글 내용 : {{article.content}}</p>
        {% comment %} <p>글 생성 시간 : {{article.created_at}}</p> {% endcomment %}
        <hr>
    {% endfor %}

{% endblock content %}

Django/03-28/articles/templates/articles/new.html
{% extends "base.html" %}

{% block content %}
<h1>New</h1>

<form action="{% url "articles:create" %}" method = 'POST'>
    {% csrf_token %}
    <label for="title">Title : </label>
    <input type="text" name='title'>

    <label for="content">Content : </label>
    <textarea name="content"></textarea>

    <input type="submit">
</form>

<hr>
{% comment %} HOME 버튼 {% endcomment %}
<a href="{% url "articles:index" %}">HOME</a>
{% endblock content %}