Javascript/05-08/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name = 'change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Javascript/05-08/accounts/urls.py
from django.urls import path

# . : 현재 디렉토리리
from . import views

# {% url namespace:name %}
# app_name = 'namespace'
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('signup/', views.signup, name = 'signup'), # 회원가입
    # request : 이미 로그인 되어있는 user의 데이터
    path('delete/', views.delete, name = 'delete'), # 회원탈퇴
    path('update/', views.update, name = 'update'), # 회원정보변경
    path('profile/<username>/', views.profile, name = 'profile'), # 프로필 페이지
    path('<int:user_pk>/follow/', views.follow, name = 'follow'), # 팔로잉 하기
]

Javascript/05-08/articles/urls.py
from django.urls import path

# . : 현재 디렉토리리
from . import views

# {% url namespace:name %}
# app_name = 'namespace'
app_name = 'articles'

urlpatterns = [
    # READ
    # 전체 게시글 조회
    path('', views.index, name = 'index'),
    # 단일 게시글 조회
    # variable routing <데이터타입:변수>
    path('<int:pk>/', views.detail, name = 'detail'),

    #CREATE
    # 랜더링 + 리다이렉트(views.py)
    path('create/', views.create, name = 'create'),

    # 단일 게시글 조회 후 삭제
    # variable routing
    path('<int:pk>/delete/', views.delete, name='delete'),

    #UPDATE
    #단일 게시글 조회 후 수정
    # variable routing
    # 페이지 렌더링 + 리다이렉트
    path('<int:pk>/update/', views.update, name='update'),

    path('<int:pk>/comments/', views.comments_create, name = 'comments_create'),
    path(
        '<int:article_pk>/comments/<int:comment_pk>/delete/',
        views.comments_delete,
        name = 'comments_delete'
    ),
    path('<int:article_pk>/likes/', views.likes, name = 'likes'),
]

Javascript/05-08/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    # M : N 관계
    # 역참조 : user.article_set(1. user가 작성한 게시글 2. user가 좋아요 누른 게시글 --> 충돌)
    # related_name = 'like_articles'
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name = 'like_articles'
    )
    
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(blank=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# ORM
# DB는 SQL쿼리로 조작
# Django는 python
# : python 코드를 SQL쿼리로 변환해주는 도구
# 왜 ORM을 쓸까?
# 우리 사용하는 Django는 python // DB는 SQL
# QuerySet API
# : 이 구문을 사용하면 DB에 데이터를 접근하고, 조작(CRUD)할 수 있다.
# ex) Article.obects.all()


# Create (객체생성)
# 1. 첫 번째 방법

# article = Board()
# article.title = 'first'
# article.content = 'hello'
# article.save()

# 2. 두 번째 방법

# article = Board(title = 'second', content = 'hi')
# article.save()

# 3. 세 번째 방법

# Board.objects.create(title = 'third', content = 'byebye')

# Q) 우리는 객체를 생성할 때 1번, 2번, 3번 방법
# 몇번 방법을 써야할까?? // 몇번 방법을 지양해야할까??
# 3번 방법은 지양, 왜??
# 객체를 저장하기전에 데이터를 검증하고 그다음에 save()
# 검증단계 : 유효성 검사(validation check)... 등등


# Read (조회)

# 1. 전체 조회

# Board.objects.all()

# 2. 특정 조건으로 데이터 조회(filter)
# Board.objects.filter(title = 'first')
# Board.objects.filter(content__contains='he')
# Board.objects.filter(title__startswith='f')

# 조회한 객체가 없을경우 예외 발생 X

# 3. 단일 데이터 조회(get)
# Board.obejects.get(pk=1)
# Board.obejects.get(title='first')

# Board.obejects.get(title='fir') ---> 에러

# 조회한 객체가 없을경우 예외 발생 O
# 조회하는 객체가 두개 이상이다. 예외 발생 O
# 고유성을 보장하는 조회.

# Update (수정)
# article = Board.objects.get(pk=1)
# article.title = 'first1'
# article.save()


# Delete (삭제)

# article = Board.objects.get(pk=1)
# article.delete()

# 만약 새로운 객체를 생성하면 pk=1로 생성되는게 아니라
# pk=4로 생성된다.

# 추가적으로 QuerySetAPI 공부는 Django 공식문서 확인인

Javascript/05-08/articles/forms.py
from django import forms
from .models import Article, Comment

# form 태그와 django model form 차이
# model form 왜쓸까??

# form 태그는 name으로 넘겨주고 views.py에서 DB저장
# model form은 바로 db에 저장
# 편해서(유효성검사도 쉽게)

class ArticleForm(forms.ModelForm):
    # class Meta : 폼의 기본 구조를 자동으로 생성
    # 위젯으로 세부 조정 가능
    class Meta:
        model = Article
        # fields = ('title', 'content', 'create_at', 'updated_at')
        fields = ('title', 'content', )
        # 한두개 정도 필드를 제외하고싶다 exclude

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

Javascript/05-08/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST

# 현재 디렉토리의 models.py로 부터 Board 모델을 가져오겠다. 
from .models import Article, Comment

def index(request):
    # QuerySetAPI ---> Read, 전체 데이터 조회 : Board.objects.all()
    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, 'articles/index.html', context)

def detail(request, pk):
    # QuerySet API : 단일 데이터 조회 : get
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    # 별표 다섯개!!!! 역참조
    comments = article.comment_set.all()
    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : comments,
    }

    return render(request, 'articles/detail.html', context)


from .forms import ArticleForm, CommentForm

@require_http_methods(['GET', 'POST'])
def create(request):
    # GET 방식 : url에 노출 --- 데이터 조회, 검색
    # POST 방식 : url에 노출 x(보안성) --- 데이터 생성, 수정, 삭제
    # POST방식이 짱이지만 GET방식을 쓰는 이유
    # GET방식에 비해 POST방식 훨씬 복잡하다. : ex) (csrf토큰) - (보안토큰)
    
    # 내가(클라이언트가) 게시글 생성 버튼(submit버튼)을 눌렀을 때
    if request.method == 'POST':
        # request.POST : 클라이언트가 POST방식으로 전송한 폼데이터
        # request.FILES : 클라이언트가 업로드한 모든 파일
        form = ArticleForm(request.POST, request.FILES)
        # 유효성 검사
        if form.is_valid(): # 유효성 검사에 성공
            # DB에 바로 저장 ---> request.user정보(중간 단계를 거쳐 저장)
            article = form.save(commit=False)
            # 로그인한 사용자(request.user)
            article.user = request.user
            # DB에 저장
            article.save()  
            # 데이터가 변경 되었기 때문에 redirect
            return redirect('articles:detail', article.pk)

    # 버튼 누르기 전에 or 다른 버튼을 눌렀을떄(다른 method)
    else:
        form = ArticleForm()
    # GET요청일때(+실패 했을 때)
    # 빈 폼
    context = {
        'form' : form
    }
    return render(request, 'articles/create.html', context)


# 단일 게시글 조회 후 삭제
@login_required
@require_POST
def delete(request, pk):
    # 게시글 조회 후 삭제
    article = Article.objects.get(pk=pk)
    # 내가 쓴 글만 내가 삭제할 수 있다.
    if request.user == article.user:
        article.delete()

    return redirect('articles:index')


# 페이지 렌더링 + 리다이렉트(create와 차이 : 기존에 있던 게시글을 변경)
@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    # request.user : 현재 로그인 되어있는 유저
    # article.user : 게시글을 작성한 유저
    if request.user == article.user:
        # submit 버튼 눌렀을떄
        if request.method == 'POST':
            # 기존 게시글의 데이터(instanc=article)
            form = ArticleForm(request.POST, request.FILES, instance=article)
            # 유효성 검사
            if form.is_valid():
                form.save() # 유효성 검사 성공하면 DB에 저장
                # 데이터 변경 되었으니 redirect
                return redirect('articles:detail', article.pk)
        # submit 버튼을 누르기전 or 다른버튼 눌렀을 때
        else:
            # 기존의 게시글의 글
            form = ArticleForm(instance=article) 
    # 게시글을 작성하지않은 다른 사용자가 update 버튼을 눌렀을떄
    else:
        return redirect('articles:index')
    # GET요청일떄
    context = {
        'article' : article,
        'form' : form,
    }
    return render(request, 'articles/update.html', context)



@login_required
@require_POST
def comments_create(request, pk):
    # 게시글 조회
    article = Article.objects.get(pk=pk)
    # 댓글 조회
    comment_form = CommentForm(request.POST)
    # 유효성 검사 성공
    if comment_form.is_valid():
        # commit = False : DB에 바로 저장하지않고 추가 작업 후 저장
        comment = comment_form.save(commit=False)
        # 참조 1. 게시글 객체
        comment.article = article
        # 2. 로그인한 사용자(request.user)
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    # 유효성 검사 실패
    context = {
        'article' : article,
        'comment_form' : comment_form
    }
    return render(request, 'articles/detail.html', context)

@login_required
@require_POST
def comments_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    # 로그인사용자 == 댓글작성한유저
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)

from django.http import JsonResponse

@login_required
def likes(request, article_pk):
    # 단일 게시글 조회
    article = Article.objects.get(pk=article_pk)
    # 좋아요 <-> 좋아요 취소
    # 현재 로그인한 user가 이미 좋아요를 눌렀다면
    if request.user in article.like_users.all():
        # 좋아요 취소(user를 제거)
        article.like_users.remove(request.user)
        is_liked = False
    else:
        # 좋아요 추가(user를 추가)
        article.like_users.add(request.user)
        is_liked = True
    
    context = {
        'is_liked': is_liked
    }

    return JsonResponse(context)
    # 새로고침
    # return redirect('articles:index')

Javascript/05-08/articles/templates/articles/create.html
{% extends "base.html" %}

{% block content %}
<h1>New</h1>

{% comment %} enctype = 'multipart/form-data' : 폼 데이터 와 함께 파일(이미지, zip파일...)도 서버에 전송 {% endcomment %}
<form action="{% url 'articles:create' %}" method = 'POST' enctype = 'multipart/form-data'>
    {% csrf_token %}
    {% comment %} django model form이 자동으로 만들어 준다 ---> db저장 {% endcomment %}
    {% comment %} form.as_table, form.as_ul, form.as_div, form.as_p {% endcomment %}
    {{ form.as_p}}

    <input type="submit">
</form>

<hr>
{% comment %} HOME 버튼 {% endcomment %}
<a href="{% url "articles:index" %}">HOME</a>

{% endblock content %}

Javascript/05-08/articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content%}
    <h2>Detail 페이지</h2>
    <h3>{{article.pk}}번째 게시글</h3>

    <hr>
    <p>작성자 : {{article.user}}</p>
    <p>제목 : {{article.title}}</p>
    <p>내용 : {{article.content}}</p>
    <p>작성 시각 : {{article.created_at}}</p>
    <p>수정 시각 : {{article.updated_at}}</p>

    {% comment %} 내가 쓴글 내가 볼때만 삭제버튼과 수정버튼이 보인다. {% endcomment %}
    {% if request.user == article.user %}
        {% comment %} 삭제버튼 {% endcomment %}
        <form action="{% url 'articles:delete' article.pk %}" method = 'POST'>
            {% csrf_token %}
            <input type="submit" value='삭제'>
        </form>
        <hr>
        {% comment %} EDIT 버튼 {% endcomment %}
        <a href="{% url "articles:update" article.pk %}">EDIT</a>
    {% endif %}

    {% if article.image %}
        <img src="{{article.image.url}}" alt="img">
    {% endif %}

    <h4>댓글 목록</h4>
    <ul>
        {% for comment in comments%}
        <li>
            {{comment.user}} - {{comment.content}}
            {% comment %} 로그인한 사용자가 댓글작성한 사용자일 경우만 삭제버튼이 보인다 {% endcomment %}
            {% if request.user == comment.user %}
            <form action="{% url "articles:comments_delete" article.pk comment.pk%}" method='POST'>
                {% csrf_token %}
                <input type="submit" value="댓글 삭제">
            </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>

    <h4>댓글 생성</h4>
    <form action="{% url "articles:comments_create" article.pk%}" method='POST'>
        {% csrf_token %}
        {{comment_form}}
        <input type="submit" value="댓글 생성">
    </form>

    <hr>
    <a href="{% url "articles:index" %}"> Home </a>
    <hr>

{% endblock content%}

Javascript/05-08/articles/templates/articles/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

    <h1>게시판</h1>

    {% comment %} 사용자가 인증 되어 있을 때(로그인 되어 있을 떄) {% endcomment %}
    {% if request.user.is_authenticated %}
    
      <h3>안녕하세요. {{user.username}}</h3>

      <a href="{% url "accounts:profile" user.username%}">내 프로필</a>

      {% comment %} GET 요청 {% endcomment %}
      <a href="{% url "accounts:update" %}">회원 정보 수정</a>

      {% comment %} POST 요청 {% endcomment %}
      <form action="{% url "accounts:delete" %}" method = "POST">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴">
      </form>
    
      {% comment %} POST요청 {% endcomment %}
      <form action="{% url "accounts:logout" %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="로그아웃">
        </form>

    <hr>
        <a href="{% url 'articles:create'%}">글쓰기</a>
    <hr>

    {% else %}

    {% comment %} GET 요청 {% endcomment %}
    <a href="{% url "accounts:signup" %}">회원 가입</a>

    {% comment %} GET요청 {% endcomment %}
    <a href="{% url "accounts:login" %}"> 로그인 </a>


    {% endif %}

    <article id="article-container">
    {% comment %} DTL : for문 {% endcomment %}
    {% for article in  articles %}
        {% comment %} {{객체.속성}} {% endcomment %}
        <p>작성자 : 
            <a href="{% url "accounts:profile" article.user.username %}">
                {{article.user}}
            </a>
        </p>

        <p>글 id : {{article.pk}}</p>

        <a href="{% url "articles:detail" article.pk %}">
            <p>글 제목 : {{article.title}}</p>
        </a>

        <p>글 내용 : {{article.content}}</p>
        
        {% comment %} data- : 사용자 정의 데이터 속성 {% endcomment %}
        <form data-article-id="{{article.pk}}">
            {% csrf_token %}
            {% comment %} 좋아요 이미 눌렀으면 -> 좋아요 취소 {% endcomment %}
            {% if request.user in article.like_users.all %}
                <input type="submit" value="좋아요 취소" id="like-{{article.pk}}">
            {% else %} {% comment %} 좋아요 안눌렀으면 -> 좋아요 {% endcomment %}
                <input type="submit" value="좋아요" id="like-{{article.pk}}">
            {% endif %}

        </form>{% comment %} 좋아요 안눌렀으면 -> 좋아요 {% endcomment %}

        {% comment %} <p>글 생성 시간 : {{article.created_at}}</p> {% endcomment %}
        <hr>
    {% endfor %}
    </article>


    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>

        // 1. querySelector
        const articleContainer = document.querySelector('#article-container')
        // csrf token
        const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;

        // 2. 콜백함수
        const handleArticleLike = async function(event){
            // submit할때 새로고침 안되게
            event.preventDefault()
            // console.log(event)
            // CurrentTarget이 아니라 target으로 ---> 버블링
            const articleId = event.target.dataset.articleId

            try {
                const response = await axios ({
                    method: 'post',
                    url: `/articles/${articleId}/likes/`,
                    headers: {'X-CSRFToken': csrftoken},
                })
                // console.log(response)
                const isLiked = response.data.is_liked
                const likeBtn = document.querySelector(`#like-${articleId}`)

                if (isLiked == true) {
                    likeBtn.value = "좋아요 취소"
                } else {
                    likeBtn.value = "좋아요"
                }

            } catch (error){
                console.log(error)
            }
        }


        // 3. 이벤트리스너
        articleContainer.addEventListener('submit', handleArticleLike)


    </script>

{% endblock content %}

Javascript/05-08/articles/templates/articles/update.html
{% extends "base.html" %}

{% block content %}
<h1>Edit</h1>

<form action="{% url "articles:update" article.pk%}" method='POST' enctype = 'multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
        
    <input type="submit">

</form>

<hr>
{% comment %} HOME 버튼 {% endcomment %}
<a href="{% url "articles:index" %}">HOME</a>

{% endblock content %}